name = "&2Shop -> %category%"
size = 6

[background]
material = "BLACK_STAINED_GLASS_PANE"
display = " "

[items]
cornerA = 10
cornerB = 34
collapsed = true
onRightClick = "BUY"
onLeftClick = "SELL"
onMiddleClick = "SELL_ALL"

[[button]]
material = "KNOWLEDGE_BOOK"
display = " "
lore = [
    "&f&l    ● &c&lBack&f&l ●    &r",
    " "
]
onClick = "BACK"
slot = 49
