name = "&2Shop -> %category%"
size = 6

[background]
material = "BLACK_STAINED_GLASS_PANE"
display = " "

[items]
cornerA = 10
cornerB = 34
collapsed = true
onRightClick = "SELL"
onLeftClick = "BUY"
onMiddleClick = "SELL_ALL"
lore = [
    "&fBuy price: &a%price_buy_single%%currency%",
    "&fSell price: &c%price_sell_single%%currency%"
]

[[button]]
material = "KNOWLEDGE_BOOK"
display = " "
lore = [
    "&f&l    ● &c&lBack&f&l ●    &r",
    " "
]
onClick = "BACK"
slot = 49
