[
  {
    "categoryName": "Oreo",
    "formattedName": "&6Oreo",
    "items": [],
    "orderNo": 1
  },
  {
    "categoryName": "Ice Cream",
    "formattedName": "&6Ice Cream",
    "items": [],
    "orderNo": 2
  },
  {
    "categoryName": "Chocolate",
    "formattedName": "&6Chocolate",
    "items": [],
    "orderNo": 3
  },
  {
    "categoryName": "Pancakes",
    "formattedName": "&6Pancakes",
    "items": [],
    "orderNo": 4
  },
  {
    "categoryName": "Salty Sticks",
    "formattedName": "&6Salty Sticks",
    "items": [],
    "orderNo": 5
  },
  {
    "categoryName": "Go To Hell",
    "formattedName": "&6Go To Hell",
    "items": [],
    "orderNo": 6
  }
]