
[logging]
normal = true
dev = true

[database]
ip = '127.0.0.1'
port = '3306'
jdbc = 'mariadb'
driver = 'org.mariadb.jdbc.Driver'
database = 'dynamic_shop'
username = ':/'
passwd = ':/'

[database.properties]
cachePrepStmts = true
prepStmtCacheSize = 250
prepStmtCacheSqlLimit = 2048
useServerPrepStmts = true
useLocalSessionState = true
rewriteBatchedStatements = true
cacheResultSetMetadata = true
cacheServerConfiguration = true
elideSetAutoCommits = true
maintainTimeStats = false

[shop]
default_stock = 300
stock_curve = 1.03
no_stock_curve = 1.2
golden_demand = 0.6
history_length = 100

