guiName = "&3&lStore"

[background]
material = "BLACK_STAINED_GLASS_PANE"
displayName = " "

# Category slot No.1
[item.11]
placeholder = true
  [item.11.onLeftClick]
  action = "OPEN"
  [item.11.onRightClick]
  action = "OPEN"
  [item.11.onMiddleClick]
  action = "STATISTICS"

# Category slot No.2
[item.12]
placeholder = true
  [item.12.onLeftClick]
  action = "OPEN"
  [item.12.onRightClick]
  action = "OPEN"
  [item.12.onMiddleClick]
  action = "STATISTICS"

# Category slot No.3
[item.13]
placeholder = true
  [item.13.onLeftClick]
  action = "OPEN"
  [item.13.onRightClick]
  action = "OPEN"
  [item.13.onMiddleClick]
  action = "STATISTICS"

# Category slot No.4
[item.14]
placeholder = true
  [item.14.onLeftClick]
  action = "OPEN"
  [item.14.onRightClick]
  action = "OPEN"
  [item.14.onMiddleClick]
  action = "STATISTICS"

# Category slot No.5
[item.15]
placeholder = true
  [item.15.onLeftClick]
  action = "OPEN"
  [item.15.onRightClick]
  action = "OPEN"
  [item.15.onMiddleClick]
  action = "STATISTICS"

# Closes the UI
[item.23]
material = "KNOWLEDGE_BOOK"
displayName = " "
lore = [
  " &2&lExit shop ",
  " "
]
  [item.23.onLeftClick]
  action = "CLOSE"
  [item.23.onRightClick]
  action = "CLOSE"
  [item.23.onMiddleClick]
  action = "CLOSE"