guiName = "&6Hello &2There!"
size = 3

[background]
material = "BLACK_STAINED_GLASS_PANE"
displayName = " "

# [item.3]
# material = "BIRCH_WOOD"

# Category slot No.1
[item.11]
material = "GRASS_BLOCK"
lore = ["&Buu you suck!"]
placeholder = true
  [onLeftClick]
  action = "OPEN"
  [onRightClick]
  action = "OPEN"
  [onMiddleClick]
  action = "STATISTICS"

# Category slot No.2
[item.12]
material = "CAKE"
lore = ["&Buu you suck!"]
placeholder = true
  [onLeftClick]
  action = "OPEN"
  [onRightClick]
  action = "OPEN"
  [onMiddleClick]
  action = "STATISTICS"

# Category slot No.3
[item.13]
material = "DIAMOND_ORE"
lore = ["&Buu you suck!"]
placeholder = true
  [onLeftClick]
  action = "OPEN"
  [onRightClick]
  action = "OPEN"
  [onMiddleClick]
  action = "STATISTICS"

# Category slot No.4
[item.14]
material = "SLIME_BLOCK"
lore = ["&Buu you suck!"]
placeholder = true
[onLeftClick]
action = "OPEN"
[onRightClick]
action = "OPEN"
[onMiddleClick]
action = "STATISTICS"

# Category slot No.5
[item.15]
material = "IRON_BLOCK"
lore = ["&Buu you suck!"]
placeholder = true
[onLeftClick]
action = "OPEN"
[onRightClick]
action = "OPEN"
[onMiddleClick]
action = "STATISTICS"