name = "&6&lUI Name"
size = 3

[background]
material = "BLACK_STAINED_GLASS_PANE"
display = " "

[[button]]
material = "KNOWLEDGE_BOOK"
display = " "
lore = [
  "&f&l    ● &c&lClose shop&f&l ●    &r",
  " "
]
onClick = "CLOSE"
slot = 22

[[category]]
onclick = "OPEN"
slot = 11

[[category]]
onclick = "OPEN"
slot = 12

[[category]]
onclick = "OPEN"
slot = 13

[[category]]
onclick = "OPEN"
slot = 14

[[category]]
onclick = "OPEN"
slot = 15



