guiName = "&6Hello &2There!"

[item.0]
material = "WARPED_STEM"

[item.1]
material = "WARPED_STEM"

[item.2]
material = "WARPED_STEM"

[item.3]
material = "WARPED_STEM"

[item.4]
material = "WARPED_STEM"

[item.23]
material = "WARPED_STEM"