name = "&6&lShop -> %category%"
size = 3

[background]
material = "BLACK_STAINED_GLASS_PANE"
display = " "

[items]
cornerA = 10
cornerB = 34
collapsed = true
onClick = "OPEN"
onMiddleClick = "STATISTICS"

[[button]]
material = "KNOWLEDGE_BOOK"
display = " "
lore = [
  "&f&l    ● &c&lBackf&l ●    &r",
  " "
]
onClick = "BACK"
slot = 49
