guiName = "&3&lStore &r&8-> %category%"

[background]
material = "BLACK_STAINED_GLASS_PANE"
displayName = " "

[item.10]
placeholder = true
  [item.10.onLeftClick]
  action = "BUY"
  [item.10.onRightClick]
  action = "SELL"
  [item.10.onMiddleClick]
  action = "STATISTICS"

[item.25]
placeholder = true
  [item.16.onLeftClick]
  action = "BUY"
  [item.16.onRightClick]
  action = "SELL"
  [item.16.onMiddleClick]
  action = "STATISTICS"

# Back button, moves down dynamicly
[item.40]
material = "KNOWLEDGE_BOOK"
displayName = " "
lore = [
  " &2&lBack ",
  " "
]
  [item.31.onLeftClick]
  action = "BACK"
  [item.31.onRightClick]
  action = "BACK"
  [item.31.onMiddleClick]
  action = "BACK"