guiName = "&3&lStore &r&8-> %category%"

[background]
material = "BLACK_STAINED_GLASS_PANE"
displayName = " "

[item.10]
placeholder = true
  [item.10.onLeftClick]
  action = "BUY"
  [item.10.onRightClick]
  action = "SELL"
  [item.10.onMiddleClick]
  action = "STATISTICS"

[item.34]
placeholder = true
  [item.34.onLeftClick]
  action = "BUY"
  [item.34.onRightClick]
  action = "SELL"
  [item.34.onMiddleClick]
  action = "STATISTICS"

# Back button, moves down dynamicly
[item.49]
material = "KNOWLEDGE_BOOK"
displayName = " "
lore = [
  " &2&lBack ",
  " "
]
  [item.49.onLeftClick]
  action = "BACK"
  [item.49.onRightClick]
  action = "BACK"
  [item.49.onMiddleClick]
  action = "BACK"